import { Inter } from 'next/font/google';
import './globals.css';
import Switcher from '@/components/includes/Switcher';
import RightSideBar from '@/components/includes/RightSideBar';
import Header from '@/components/includes/Header';
import Sidebar from '@/components/includes/Sidebar';
import Footer from '@/components/includes/Footer';
import ScrollToTop from '@/components/includes/ScrollToTop';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
    <>
      {/* <Demo /> */}

      {/* <!DOCTYPE html> */}
      <html
        lang='en'
        dir='ltr'
        data-nav-layout='vertical'
        data-theme-mode='light'
        data-header-styles='light'
        data-menu-styles='gradient'
        data-toggled='close'
      >
        <head>
          {/* <!-- Meta Data --> */}
          <meta charSet='UTF-8' />
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1.0'
          />
          <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
          <title>
            {' '}
            Xino - Premium dashboard ui bootstrap rwd admin html5 template{' '}
          </title>
          <meta
            name='Description'
            content='Bootstrap Responsive Admin Web Dashboard HTML5 Template'
          />
          <meta name='Author' content='Spruko Technologies Private Limited' />
          <meta
            name='keywords'
            content='html admin template, dashboard, bootstrap 5 dashboard, admin dashboard bootstrap, crypto, admin, admin panel template, crypto dashboard, dashboard crypto, cryptocurrency dashboard, admin template, bootstrap dashboard, dashboard template bootstrap, crypto dashboard template, bootstrap admin template'
          />

          {/* <!-- Favicon --> */}
          <link
            rel='icon'
            href='/assets/images/brand-logos/favicon.ico'
            type='image/x-icon'
          />

          {/* <!-- Choices JS --> */}
          <script src='/assets/libs/choices.js/public/assets/scripts/choices.min.js'></script>

          {/* <!-- Main Theme Js --> */}
          <script src='/assets/js/main.js'></script>

          {/* <!-- Bootstrap Css --> */}
          <link
            id='style'
            href='/assets/libs/bootstrap/css/bootstrap.min.css'
            rel='stylesheet'
          />

          {/* <!-- Style Css --> */}
          <link href='/assets/css/styles.min.css' rel='stylesheet' />

          {/* <!-- Icons Css --/> */}
          <link href='/assets/css/icons.css' rel='stylesheet' />

          {/* <!-- Node Waves Css --/> */}
          <link href='/assets/libs/node-waves/waves.min.css' rel='stylesheet' />

          {/* <!-- Simplebar Css --/> */}
          <link
            href='/assets/libs/simplebar/simplebar.min.css'
            rel='stylesheet'
          />

          {/* <!-- Color Picker Css --/> */}
          <link
            rel='stylesheet'
            href='/assets/libs/flatpickr/flatpickr.min.css'
          />
          <link
            rel='stylesheet'
            href='/assets/libs/@simonwep/pickr/themes/nano.min.css'
          />

          {/* <!-- Choices Css --/> */}
          <link
            rel='stylesheet'
            href='/assets/libs/choices.js/public/assets/styles/choices.min.css'
          />

          <link
            rel='stylesheet'
            href='/assets/libs/apexcharts/apexcharts.css'
          />

          <link
            rel='stylesheet'
            href='/assets/libs/jsvectormap/css/jsvectormap.min.css'
          />

          <link
            rel='stylesheet'
            href='/assets/libs/swiper/swiper-bundle.min.css'
          />
        </head>

        <body>
          <Switcher />

          {/* <!-- Loader --> */}
          <div id='loader'>
            <img src='/assets/images/media/loader.svg' alt='' />
          </div>
          {/* <!-- Loader --> */}
          <RightSideBar />

          <div className='page'>
            <Header />
            <Sidebar />
            {children}

            <Footer />
          </div>

          <ScrollToTop />

          {/* <!-- Popper JS --> */}
          {/* <script src='/assets/libs/@popperjs/core/umd/popper.min.js'></script> */}

          {/* <!-- Bootstrap JS --> */}
          {/* <script src='/assets/libs/bootstrap/js/bootstrap.bundle.min.js'></script> */}

          {/* <!-- Defaultmenu JS --> */}
          {/* <script src='/assets/js/defaultmenu.min.js'></script> */}

          {/* <!-- Node Waves JS--> */}
          {/* <script src='/assets/libs/node-waves/waves.min.js'></script> */}

          {/* <!-- Sticky JS --> */}
          {/* <script src='/assets/js/sticky.js'></script> */}

          {/* <!-- Simplebar JS --> */}
          {/* <script src='/assets/libs/simplebar/simplebar.min.js'></script>
          <script src='/assets/js/simplebar.js'></script> */}

          {/* <!-- Color Picker JS --> */}
          {/* <script src='/assets/libs/@simonwep/pickr/pickr.es5.min.js'></script> */}

          {/* <!-- JSVector Maps JS --> */}
          {/* <script src='/assets/libs/jsvectormap/js/jsvectormap.min.js'></script> */}

          {/* <!-- JSVector Maps MapsJS --> */}
          {/* <script src='/assets/libs/jsvectormap/maps/world-merc.js'></script> */}

          {/* <!-- Apex Charts JS --> */}
          {/* <script src='/assets/libs/apexcharts/apexcharts.min.js'></script> */}

          {/* <!-- Chartjs Chart JS --> */}
          {/* <script src='/assets/libs/chart.js/chart.min.js'></script> */}

          {/* <!-- Swiper JS --> */}
          {/* <script src='/assets/libs/swiper/swiper-bundle.min.js'></script> */}

          {/* <!-- Index-Dashboard --> */}
          {/* <script src='/assets/js/index.js'></script> */}

          {/* <!-- Custom JS --> */}
          {/* <script src='/assets/js/custom.js'></script> */}

          {/* <!-- Custom-Switcher JS --> */}
          {/* <script src='/assets/js/custom-switcher.min.js'></script> */}
        </body>
      </html>
    </>
  );
}
